on:
  push:
    branches: [develop]
    tags:
      - '*'
  pull_request:
    branches: [develop]
name: Plugin CI
jobs:
  ios:
    name: iOS Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - "platform=iOS Simulator,OS=14.4,name=iPhone 8"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          
      - name: Install NPM Dependencies
        run: npm install

      - name: Build NPM Module
        run: npm run build

  android:
    name: Android Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"

      - name: Install NPM Dependencies
        run: npm install

      - name: Build NPM Module
        run: npm run build
  
  publish:
    if: startsWith( github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Set npm version
        run: npm version $RELEASE_VERSION

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}